package com.sketchbook.sync.migration

import com.sketchbook.core.ProjectUuid
import java.io.File
import java.nio.file.Files
import kotlin.test.AfterTest
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertNotNull
import kotlin.test.assertNull
import kotlin.test.assertTrue

class JvmAudioIdSidecarTest {
    private val tmp = Files.createTempDirectory("sketchbook-sidecar").toFile()
    private val sidecar = JvmAudioIdSidecar()

    @AfterTest
    fun cleanup() {
        tmp.deleteRecursively()
    }

    @Test
    fun returnsNullWhenSidecarMissing() {
        assertNull(sidecar.read(tmp.absolutePath))
        assertEquals(false, sidecar.exists(tmp.absolutePath))
    }

    @Test
    fun roundTripsUuid() {
        val uuid = ProjectUuid("abc-123")
        assertTrue(sidecar.write(tmp.absolutePath, uuid))
        assertEquals(uuid, sidecar.read(tmp.absolutePath))
        assertTrue(sidecar.exists(tmp.absolutePath))
    }

    @Test
    fun stripsTrailingWhitespaceAndComments() {
        File(tmp, AUDIO_ID_SIDECAR_NAME).writeText("# generated by tool\nfoo-uuid  \n\n")
        assertEquals(ProjectUuid("foo-uuid"), sidecar.read(tmp.absolutePath))
    }

    @Test
    fun stripsBom() {
        val bom = ""
        File(tmp, AUDIO_ID_SIDECAR_NAME).writeText("${bom}abc-with-bom\n")
        assertEquals(ProjectUuid("abc-with-bom"), sidecar.read(tmp.absolutePath))
    }

    @Test
    fun returnsFalseWhenDirectoryDoesNotExist() {
        val missing = File(tmp, "does-not-exist-subdir").absolutePath
        assertEquals(false, sidecar.write(missing, ProjectUuid("x")))
    }
}
